name: "godot-ci export"
on: push

env:
  GODOT_VERSION: 3.4.4
  EXPORT_NAME: test-project

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:mono-3.4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          
      - name: print secrets
        run: |
          printf 'extends Node\nconst API_KEY := \"%s\"' $DEV_ENV_FILE > UI/Firebase/PrivateKey.gd
          cat UI/Firebase/PrivateKey.gd
        shell: bash
        env:
          DEV_ENV_FILE : ${{secrets.FIREBASE_API_KEY}}
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: DEV_ENV_FILE
          path: UI/Firebase/PrivateKey.gd
          
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          cd $EXPORT_NAME
          godot -v --export "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: build/windows
