name: "godot gut test"
on: push

jobs:
  execute-gut:
    name: Run GUT tests
    runs-on: ubuntu-latest
    steps:
      - name: print secrets
        run: |
          $PrivateKey.gd >> UI/Firebase
          cat UI/Firebase
        shell: bash
        env:
          PrivateKey.gd : ${{secrets.FIREBASE_API_KEY}}
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: PrivateKey.gd
          path: UI/Firebase
          
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker test
        uses: ceceppa/godot-gut-ci@master
        with:
          godot_version: 3.4.4
          integration_test: res://Test/Unit
          unit_test: res://Test/Unit
